mybatis:
  type-aliases-package: com.goods.demo.pojo
  mapper-locations: classpath:mappers/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yedeyang
    url: jdbc:mysql://127.0.0.1:3306/mmall?characterEncoding=utf-8&useSSL=false

  jackson:
    default-property-inclusion: non_null

pagehelper:
  helperDialect: mysql
  reasonable: true

logging:
  level:
    com:
      ye.goods.dao: DEBUG

com.ye:
  ftp:
    imageHost: 35.185.173.15
    username: root
    password: yedeyang
    imgDirectory: img
